version: "3"
services:
  backend:
    container_name: checkit-batch
    image: jiminsong/checkitbatch:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    container_name: checkit-redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server
